spring:
  application:
    name: smart-room
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iot
    username: iot
    password: iot@123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 12345
